export const DEFAULT_TIMEOUT_MS = 10_000
export const DEFAULT_RECALL_LIMIT = 10
export const DEFAULT_RECALL_QUALITY_POLICY = 'strict-v1'
export const DEFAULT_RECALL_LOW_SCORE_THRESHOLD = 0.25
export const DEFAULT_RECALL_HIGH_SCORE_THRESHOLD = 0.6
export const DEFAULT_RECALL_CANDIDATE_MULTIPLIER = 3
export const DEFAULT_RECALL_MAX_MEDIUM_RESULTS = 4
export const DEFAULT_RECALL_MAX_UNKNOWN_RESULTS = 2
